apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::239828331157:role/udacity-node-group
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-09-12T19:36:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1541"
  uid: 7f9af374-b178-43ad-aac9-38d4d1f04305
  - userarn: arn:aws:iam::239828331157:user/github-action-user
    username: github-action-role
    groups:
      - system:masters
