# Workflow name
name: Backend Continuous Integration

# Triggers for the workflow only on pull request against the main branch.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    environment: Development Environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv flake8

      - name: Run Lint
        working-directory: starter/backend
        run: pipenv run lint

  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run Tests
        working-directory: starter/backend
        run: pipenv run pytest

  Build:
    needs: [Linting, Testing]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: starter/backend
        run: |
            # Build the Docker image
            docker build --tag mp-backend:latest .   
            # Run the Docker container
            docker run -p 5000:5000 --name mp-backend -d mp-backend