# Workflow name
name: Backend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Linting:
    runs-on: ubuntu-latest
    environment: Devlopmnet Environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv flake8

    - name: Run Lint
      working-directory: starter/backend
      run: pipenv run lint

  Testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run Tests
      working-directory: starter/backend
      run: pipenv install pytest && pipenv run test

      
  build-and-deploy:
    needs: [Linting, Testing]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # token vlaue  
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
            
      - name: Build and Push Docker Image
        working-directory: starter/backend
        env:
          IMAGE_TAG: latest
          REPO_NAME: backend
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag 239828331157.dkr.ecr.us-east-1.amazonaws.com/backend:latest .
          docker push 239828331157.dkr.ecr.us-east-1.amazonaws.com/backend:latest
      
      - name: Update Kubeconfig
        run:
         aws eks update-kubeconfig --name cluster --region us-east-1
      
      - name: Deploy Docker Image to Amazon EKS
        working-directory: starter/backend/k8s
        env:
          IMAGE_TAG: latest
          REPO_NAME: backend
        run: |
          kustomize edit set image backend=239828331157.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:$IMAGE_TAG
          kustomize build | kubectl apply -f -
